### PR TITLE
Changing ore rendering from translucent to cutout.

### PR DESCRIPTION
**Pull request by legendblade**
This fixes some rendering issues where:
- The ore shows up in front of rain that should be visible between you and the ore.
- Particle effects are visible through the ore
- Large walls of ore (e.g. Geolosys/GregTech generation) cause excessive rendering lag and weird artifacting at block edges.

### CODE REVIEW

**Comment by FreneticScribbler** [comment]
Hmm, I suppose I didn't really think that one through. Does that re-break ore shadowing?

**Comment by legendblade** [comment]
Ah, my apologies, I'd forgotten to test that; it does indeed look like the ore doesn't block light anymore. :(

**Comment by FreneticScribbler** [comment]
Hang on what. That should have nothing to do with it.... It should block light no matter what. Hmm.

To give more detail on my original question. Our ores have a translucent shadow layer to give them depth, that's why they were set to translucent. Does this still render with cutout set?

**Comment by legendblade** [comment]
You know, I'd originally typed out a length response in regards to the shadow layer, only to second guess myself and check if they blocked light as well.

To answer *that* question, no, unfortunately they no longer generate the shadow layer either - though in the pack I was testing this with originally, we removed the shadow layer because it clashed badly with some of the base textures we were using (especially any darker colored blocks - basalt, slate, etc). Upon retesting in a fresh pack this morning with no changes to the shadow layer, it's still missing from the blocks.

Sorry for the misunderstanding.

**Comment by SkySom** [comment]
The main issue with the shadow wasn't that it wasn't showing up. More that it was white. And looked like hell.

**Comment by FreneticScribbler** [comment]
Never had an issue with it rendering white, only that it didn't show up at all.

But given the problems with translucent texture implementations, I reckon we ditch the shadow layer altogether.

**Comment by SkySom** [comment]
Honestly come 1.14, I will be ditching, the issue is with the current already generated jsons, it's got to stay around as removing it now would break any default assets. Honestly if things are an issue for you @legendblade my suggest is adding a part data that can set the ore rendering, so you can switch it for your needs, but not break any current blocks. Feel free to reach out to me in Discord for additional info. I'd love to work through this.

**Comment by legendblade** [comment]
@SkySom not a problem - I'd generally forgotten about this as Rorax and I have decided to just wait until 1.14 to put the pack out anyway.

Thanks.

**Comment by SkySom** [comment]
Works for me I'll go ahead and close the PR for now. And we'll see revisit when I move the Material stuff over to 1.14

**Pull request closed without merging**
